Refactoring exotools, somewhat destructive but there is a backup (temp). there are a lot of changes, moved a lot of stuff into functions. added new functions fixed flow, edited the dockerfile, removed image save feature (not worth it), remove the hash check (in its current state i dont think it was useful, ill gladly help reimplement something better), quite a few code comments that need to be resolved.

diff --git a/exotools/docker/docker_files/dockerfile b/exotools/docker/docker_files/dockerfile
--- a/exotools/docker/docker_files/dockerfile
+++ b/exotools/docker/docker_files/dockerfile
@@ -1,7 +1,9 @@
 FROM rust:buster
 
 RUN cargo install cargo-audit # install cargo audit
+RUN cargo audit -db || : # update Databases can append -q for quiet
+RUN echo "Ignore Error above. just used to sync repo"
 
 VOLUME /rustvol-testing
 
-ENTRYPOINT ["cargo", "audit", "-f", "/rustvol-testing/Cargo.lock", "--json"]
+ENTRYPOINT [""]
